import os
from typing import Any, Dict, List, Set, Optional


def format_ass_time(seconds: float) -> str:
    """Converts seconds to ASS timestamp format: H:MM:SS.cc"""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis >= 100:
        secs += 1
        centis = 0
    return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"


def generate_ass_subtitles(
    timestamp_map: Dict[str, Any],
    output_ass_path: str,
    edits: Optional[List[Dict[str, Any]]] = None,
    font_size: int = 50,
    primary_color: str = "&H00FFFFFF",
    highlight_color: str = "&H0000FFFF",
    **kwargs,
) -> str:
    """
    Generates an Advanced SubStation Alpha (.ass) subtitle file formatted
    with viral TikTok/Shorts styling and animated active-word highlighting.
    """
    edits = edits or []
    os.makedirs(os.path.dirname(os.path.abspath(output_ass_path)), exist_ok=True)

    # 1. Identify chunks marked for cut
    cut_ids: Set[str] = {
        e.get("trigger_id")
        for e in edits
        if e.get("action") == "cut"
    }

    # 2. Build .ass Header and Styles
    header = """[Script Info]
; Script generated by AI Content Manager
Title: Viral AI Subtitles
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,74,&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,5,3,2,60,60,340,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    dialogue_lines: List[str] = []

    # 3. Generate word-by-word highlighted lines for each uncut chunk
    for chunk_id, chunk_data in timestamp_map.items():
        if chunk_id in cut_ids:
            continue

        words = chunk_data.get("words", [])
        if not words:
            # Fallback if no word level breakdown
            start_str = format_ass_time(chunk_data.get("start", 0.0))
            end_str = format_ass_time(chunk_data.get("end", 1.0))
            text = chunk_data.get("text", "")
            dialogue_lines.append(
                f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{text.upper()}"
            )
            continue

        # For every word, create a subtitle event highlighting that word in neon yellow
        # Format: {\c&H00FFFF&}ACTIVE_WORD{\c&HFFFFFF&}
        for active_idx, active_word_info in enumerate(words):
            word_start = active_word_info["start"]
            word_end = active_word_info["end"]

            # Prevent zero-length display
            if word_end <= word_start:
                word_end = word_start + 0.15

            start_str = format_ass_time(word_start)
            end_str = format_ass_time(word_end)

            formatted_words = []
            for idx, w in enumerate(words):
                clean_word = w["word"].upper()
                if idx == active_idx:
                    # Highlight color: Vibrant Yellow (&H0000FFFF in BGR = &H00FFFF&)
                    formatted_words.append(r"{\c&H00FFFF&}" + clean_word + r"{\c&HFFFFFF&}")
                else:
                    formatted_words.append(clean_word)

            rendered_text = " ".join(formatted_words)
            dialogue_lines.append(
                f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{rendered_text}"
            )

    full_ass_content = header + "\n".join(dialogue_lines) + "\n"

    with open(output_ass_path, "w", encoding="utf-8") as f:
        f.write(full_ass_content)

    print(f"[OK] Generated dynamic ASS subtitles with {len(dialogue_lines)} events: {output_ass_path}")
    return output_ass_path
