import os
from typing import Any, Dict, List, Set, Optional


def format_ass_time(seconds: float) -> str:
    """Converts seconds to ASS timestamp format: H:MM:SS.cc"""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis >= 100:
        secs += 1
        centis = 0
    return f"{hours}:{minutes:02d}:{secs:02d}.{centis:02d}"


def generate_ass_subtitles(
    timestamp_map: Dict[str, Any],
    output_ass_path: str,
    edits: Optional[List[Dict[str, Any]]] = None,
    font_size: int = 50,
    primary_color: str = "&H00FFFFFF",
    highlight_color: str = "&H0000FFFF",
    **kwargs,
) -> str:
    """
    Generates an Advanced SubStation Alpha (.ass) subtitle file formatted
    with viral TikTok/Shorts styling and animated active-word highlighting.
    """
    edits = edits or []
    os.makedirs(os.path.dirname(os.path.abspath(output_ass_path)), exist_ok=True)

    # 1. Identify cut intervals
    cut_intervals: List[Tuple[float, float]] = []
    for e in edits:
        if e.get("action") == "cut":
            start = e.get("start")
            end = e.get("end")
            if start is not None and end is not None:
                cut_intervals.append((float(start), float(end)))
            elif e.get("trigger_id") and e.get("trigger_id") in timestamp_map:
                chunk = timestamp_map[e["trigger_id"]]
                cut_intervals.append((float(chunk.get("start", 0.0)), float(chunk.get("end", 0.0))))

    def _map_time(t: float) -> float:
        shift = 0.0
        for c_start, c_end in sorted(cut_intervals):
            if t <= c_start:
                break
            elif c_start < t < c_end:
                shift += (t - c_start)
                break
            else:
                shift += (c_end - c_start)
        return max(0.0, t - shift)

    def _is_inside_cut(s: float, e: float) -> bool:
        for c_start, c_end in cut_intervals:
            if s >= c_start - 0.05 and e <= c_end + 0.05:
                return True
        return False

    # 2. Build .ass Header and Styles
    header = """[Script Info]
; Script generated by AI Content Manager
Title: Viral AI Subtitles
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,74,&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,5,3,2,60,60,340,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    dialogue_lines: List[str] = []

    # 3. Generate word-by-word highlighted lines for each uncut chunk
    for chunk_id, chunk_data in timestamp_map.items():
        chunk_start = chunk_data.get("start", 0.0)
        chunk_end = chunk_data.get("end", 0.0)

        if _is_inside_cut(chunk_start, chunk_end):
            continue

        raw_words = chunk_data.get("words", [])
        # Filter valid non-empty words
        words = [w for w in raw_words if w.get("word", "").strip() and not _is_inside_cut(w["start"], w["end"])]

        if not words:
            # Fallback if no word level breakdown
            text = chunk_data.get("text", "").strip()
            if text:
                start_str = format_ass_time(_map_time(chunk_start))
                end_str = format_ass_time(_map_time(chunk_end))
                dialogue_lines.append(
                    f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{text.upper()}"
                )
            continue

        # For every word, create a subtitle event highlighting that word in neon yellow
        # Format: {\c&H00FFFF&}ACTIVE_WORD{\c&HFFFFFF&}
        for active_idx, active_word_info in enumerate(words):
            word_start = active_word_info["start"]
            
            # Stretch subtitle display duration to prevent flickering between words
            if active_idx < len(words) - 1:
                # End when the next word starts
                word_end = words[active_idx + 1]["start"]
            else:
                # Last word in chunk: use its actual end time, but ensure a minimum readable duration
                word_end = chunk_data.get("end", active_word_info["end"])
                if word_end - word_start < 0.2:
                    word_end = word_start + 0.2
            
            # Prevent zero-length display fallback
            if word_end <= word_start:
                word_end = word_start + 0.15

            mapped_start = _map_time(word_start)
            mapped_end = _map_time(word_end)

            if mapped_end <= mapped_start:
                mapped_end = mapped_start + 0.15

            start_str = format_ass_time(mapped_start)
            end_str = format_ass_time(mapped_end)

            formatted_words = []
            for idx, w in enumerate(words):
                clean_word = w["word"].strip().upper()
                if not clean_word:
                    continue
                if idx == active_idx:
                    # Highlight color: Vibrant Yellow (&H0000FFFF in BGR = &H00FFFF&)
                    formatted_words.append(r"{\c&H00FFFF&}" + clean_word + r"{\c&HFFFFFF&}")
                else:
                    formatted_words.append(clean_word)

            rendered_text = " ".join(formatted_words)
            dialogue_lines.append(
                f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{rendered_text}"
            )

    full_ass_content = header + "\n".join(dialogue_lines) + "\n"

    with open(output_ass_path, "w", encoding="utf-8") as f:
        f.write(full_ass_content)

    print(f"[OK] Generated dynamic ASS subtitles with {len(dialogue_lines)} events: {output_ass_path}")
    return output_ass_path
